<a href="https://colab.research.google.com/github/RupeshReddy672/DataSciencePractice/blob/master/NumpyFunctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In Numpy 0= x axis, 1 = y axis. vice versa in pandas


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#1. np.sort()
a = np.random.randint(1,20,12)

a

array([ 7, 10, 19, 18,  5, 10,  6, 13,  5,  9, 19,  7])

In [ ]:
b= np.random.randint(1,100,36).reshape(6,6)
b

array([[72, 89, 93, 60, 25, 34],
       [49, 65, 51, 40, 70, 73],
       [42, 72, 87, 45, 89, 65],
       [ 4, 38, 37, 60, 12, 92],
       [66, 16, 15, 14, 99,  9],
       [ 2, 69, 48, 99,  6, 87]])

In [ ]:
np.sort(a)[::-1]

array([19, 19, 18, 13, 10, 10,  9,  7,  7,  6,  5,  5])

In [ ]:
np.sort(b,axis=1)[:,::-1]

array([[93, 89, 72, 60, 34, 25],
       [73, 70, 65, 51, 49, 40],
       [89, 87, 72, 65, 45, 42],
       [92, 60, 38, 37, 12,  4],
       [99, 66, 16, 15, 14,  9],
       [99, 87, 69, 48,  6,  2]])

In [ ]:
#2. np.append(arr_name, element)

print(np.append(a,101))

#in 2d arrays to append 1 more column or one element in each row.

np.append(b, np.ones((b.shape[0],1)),axis=1)

[  7  10  19  18   5  10   6  13   5   9  19   7 101]


array([[72., 89., 93., 60., 25., 34.,  1.],
       [49., 65., 51., 40., 70., 73.,  1.],
       [42., 72., 87., 45., 89., 65.,  1.],
       [ 4., 38., 37., 60., 12., 92.,  1.],
       [66., 16., 15., 14., 99.,  9.,  1.],
       [ 2., 69., 48., 99.,  6., 87.,  1.]])

In [ ]:
#3. np.concatenate() just like hstack
''' use mainly to comcatenating 2d arrays.'''

c = np.arange(18).reshape(3,6)
d = np.arange(18,36).reshape(3,6)

np.concatenate((c,d),axis=0)



array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
#4. np.unique()


'''
identifies unique elements in the array.
'''

e = np.array([1,1,1,1,3,3,3,3,6,5,2,5,3,2,5,7,8,7,7,6,4,3])
np.unique(e)
#np.unique(d).size

e.shape
e.size

22

In [ ]:
#5. np.expand_dims()
print(e.shape)
print(np.expand_dims(np.unique(e),axis=0).shape)
print(np.expand_dims(np.unique(e),axis=1).shape)

(22,)
(1, 8)
(8, 1)


In [ ]:
a

array([ 7, 10, 19, 18,  5, 10,  6, 13,  5,  9, 19,  7])

In [ ]:
#6. np.where() using 1D array
'''To get the  indices of the elements
 which satisfies the given condition.
'''
np.where(a>50)



(array([ 4,  5,  6, 11, 13, 15, 17, 18, 19, 21]),)

In [ ]:
#where using 2D array and 3 D arrays



b = np.random.randint(1,40,12).reshape(3,4)
# Find indices where elements are greater than 4
print(np.where(b > 3),end='\n\n\n')

b1 = np.random.randint(1,50,24).reshape(2,3,4)
np.where(b1>10)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 1, 2, 3]))




(array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([0, 0, 0, 1, 1, 2, 2, 2, 0, 0, 1, 1, 1, 1, 2, 2, 2]),
 array([1, 2, 3, 0, 1, 0, 1, 3, 2, 3, 0, 1, 2, 3, 1, 2, 3]))

In [ ]:
b1

array([[[ 3, 35, 15, 41],
        [33, 21, 10,  4],
        [15, 35,  8, 40]],

       [[ 1,  6, 16, 47],
        [43, 13, 39, 21],
        [10, 33, 14, 30]]])

In [ ]:
a

array([11, 25, 10,  6, 64, 76, 53, 42,  4, 46, 39, 76, 50, 51, 21, 59, 12,
       55, 88, 85, 10, 63, 42, 24, 31])

In [ ]:
#np.where()

'''To get the elements directly
 which satisfies the fiven condition.
 np.where(condition,true,false) or np.where(condition,arr,b)

np.where(
condition,if true consider the original element(x),
false change the orginal with this element(y))'''

print(np.where(a>=30,a,30),end='\n\n')
print(np.where(b>=30,b,30),end='\n\n')
np.where(b1>=15,b1,100)




[30 30 30 30 64 76 53 42 30 46 39 76 50 51 30 59 30 55 88 85 30 63 42 30
 31]

[[30 36 30 30]
 [30 30 30 30]
 [30 30 30 32]]



array([[[100,  35,  15,  41],
        [ 33,  21, 100, 100],
        [ 15,  35, 100,  40]],

       [[100, 100,  16,  47],
        [ 43, 100,  39,  21],
        [100,  33, 100,  30]]])

In [ ]:
#7. np.argmax()
'''
  Returns the index/indices of the max element
  in a array /axis of a array.
  Mostly used on 1D arrays.
'''

#on 1D
print(np.argmax(a))
print(a)
print()

#on 2D
print(np.argmax(b,axis=0))
print(b)
print()

#on 3D
print(np.argmax(b1))
print(b1)



2
[ 7 10 19 18  5 10  6 13  5  9 19  7]

[2 0 0 2]
[[23 38 35 30]
 [18 38 20 12]
 [29  9 17 33]]

13
[[[ 5 15 45 30]
  [33 44 15 27]
  [17 31 38 27]]

 [[43 49 10 15]
  [44 39 12 21]
  [ 9 20 17 29]]]


In [ ]:
#8. np.argmin()
'''just like argmax, it finds the lowest element index/indices.
'''
#np.argmax()
'''
  Returns the index/indices of the max element
  in a array /axis of a array.
  Mostly used on 1D arrays.
'''

#on 1D
print(np.argmin(a))
print(a)

#on 2D
print(np.argmin(b,axis=0))
print(b)
print()

#on 3D
print(np.argmin(b1))
print(b1)




8
[11 25 10  6 64 76 53 42  4 46 39 76 50 51 21 59 12 55 88 85 10 63 42 24
 31]
[2 2 2 0]
[[16 36 11  7]
 [24 30 27 12]
 [ 2 10  7 32]]

12
[[[ 3 35 15 41]
  [33 21 10  4]
  [15 35  8 40]]

 [[ 1  6 16 47]
  [43 13 39 21]
  [10 33 14 30]]]


In [ ]:
#9. np.cumsum()

'''
calculates the cumulative sum of arrays of a given axis.
'''

#on 1D
print(a)
print(np.cumsum(a))
print()

#on 2D
print(b)
print()
print(np.cumsum(b,axis=1))
print('\n\n')


#on 3D
print(b1)
print('\n\n\n\n')
print(np.cumsum(b1,axis=1))



[11 25 10  6 64 76 53 42  4 46 39 76 50 51 21 59 12 55 88 85 10 63 42 24
 31]
[  11   36   46   52  116  192  245  287  291  337  376  452  502  553
  574  633  645  700  788  873  883  946  988 1012 1043]

[[16 36 11  7]
 [24 30 27 12]
 [ 2 10  7 32]]

[[16 52 63 70]
 [24 54 81 93]
 [ 2 12 19 51]]



[[[ 3 35 15 41]
  [33 21 10  4]
  [15 35  8 40]]

 [[ 1  6 16 47]
  [43 13 39 21]
  [10 33 14 30]]]





[[[ 3 35 15 41]
  [36 56 25 45]
  [51 91 33 85]]

 [[ 1  6 16 47]
  [44 19 55 68]
  [54 52 69 98]]]


In [ ]:
#10. np.cumprod()

''' same as np.cumprod()'''


' same as np.cumprod()'

In [ ]:
#11. np.percentile()
print(np.sort(a))

np.percentile(a,78)

[ 4  6 10 10 11 12 21 24 25 31 39 42 42 46 50 51 53 55 59 63 64 76 76 85
 88]


np.float64(61.879999999999995)

In [ ]:
#np.histogram
a= np.random.randint(1,100,25)
'''
tells the frequency count of numbers in a given bin range.

'''

np.histogram(a,bins=[0,20,40,60,80,100])


(array([6, 7, 4, 3, 5]), array([  0,  20,  40,  60,  80, 100]))

In [ ]:
#np.corrcoef()
'''corelation coefficient is like corelation between two arrayss.
range = [-1,0,1]
if it is 1 or +ve relation
-> then with one increase other should also increase.
For -1 it is with one increase other decreases.
For 0, it is like no relation.
increase or decrease in one won't effect the other.
'''
a1= np.array([10, 20, 30,35,45])
b2= np.array([100,200,300,400,500])
np.corrcoef(a1,b2)


array([[1.        , 0.99484975],
       [0.99484975, 1.        ]])

In [ ]:
a1

array([10, 20, 30, 35, 45])

In [ ]:
#np.isin()
'''
in a given array i
t searches multiple items at once.
-> useful in pandas

'''
a1[np.isin(a1,[10,20,30,40,50,60,70,80])]



array([10, 20, 30])

In [ ]:
b1

array([[[ 3, 35, 15, 41],
        [33, 21, 10,  4],
        [15, 35,  8, 40]],

       [[ 1,  6, 16, 47],
        [43, 13, 39, 21],
        [10, 33, 14, 30]]])

In [ ]:
#np.flip()
'''
 function reverses the order of elements
  in an array along a specified axis while
 keeping the same shape
 '''
np.flip(b1,axis=0)

array([[[43, 49, 10, 15],
        [44, 39, 12, 21],
        [ 9, 20, 17, 29]],

       [[ 5, 15, 45, 30],
        [33, 44, 15, 27],
        [17, 31, 38, 27]]])

In [ ]:
a

array([70, 38, 10,  6, 64, 76, 53, 42,  4, 46, 39, 76, 50, 51, 21, 59, 12,
       55, 88, 85, 10, 63, 42, 24, 31])

In [ ]:
#np.put()
np.put(a,[0,1],[11,25])
a

array([11, 25, 10,  6, 64, 76, 53, 42,  4, 46, 39, 76, 50, 51, 21, 59, 12,
       55, 88, 85, 10, 63, 42, 24, 31])

In [ ]:
#np.delete()
np.delete(a,[0,1,3,4])


array([10, 76, 53, 42,  4, 46, 39, 76, 50, 51, 21, 59, 12, 55, 88, 85, 10,
       63, 42, 24, 31])

In [ ]:
#Set Functions- union, intersection, diff,etc,.

In [ ]:
#np.union1d
'''
np.union1d(a,b)
'''

'\nnp.union1d(a,b)\n'

In [ ]:
#np.intersection1d

In [ ]:
#np.setdiff1d

In [ ]:
#np.setxor1d
'''setxor or XOR ->
removes only the common elements in both sets
and keeps the other elements from both sets.
'''

'setxor or XOR ->\nremoves only the common elements in both sets\nand keeps the other elements from both sets.\n'

In [ ]:
#np.in1d

'''
tests whether each element of a 1-D array (ar1)
 is also present in a second array (ar2),
returning a boolean array of the same length.
'''
import numpy as np

test = np.array([0, 1, 2, 5, 0])
states = [0, 2]

# Test presence
mask = np.in1d(test, states)
print(mask)
# Output: array([ True, False,  True, False,  True])

# Extract matching elements
print(test[mask])
# Output: [0 2 0]



[ True False  True False  True]
[0 2 0]


/tmp/ipykernel_1132/1780190314.py:14: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  mask = np.in1d(test, states)


In [ ]:
#np.clip()
'''
 clips (limits) the values in an array to a specified
 interval. Values below a_min are replaced with a_min,
 and values above a_max are replaced with a_max
'''
np.clip(a,8,15)

array([11, 15, 10,  8, 15, 15, 15, 15,  8, 15, 15, 15, 15, 15, 15, 15, 12,
       15, 15, 15, 10, 15, 15, 15, 15])